# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-04 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(max_length=100, verbose_name='Nome do evento')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de inicio')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de termino')),
                ('vagas_evento', models.IntegerField(blank=True, null=True, verbose_name='Numero de vagas')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao do Evento')),
                ('nome_palestrante', models.CharField(max_length=100, verbose_name='Nome do palestrante')),
                ('tipo_evento', models.CharField(max_length=100, verbose_name='Tipo de evento')),
                ('imagem_evento', models.ImageField(blank=True, null=True, upload_to='eventos/images', verbose_name='Imagem')),
                ('endereco', models.CharField(help_text='Para uma melhor localiza\ufffd\ufffdo no mapa, preencha sem abrevia\ufffd\ufffdes. Ex: Rua Martinho Estrela,  1229', max_length=255, verbose_name='Endereco')),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(help_text='Para uma melhor localizacao no mapa, preencha sem abreviacoes. Ex: Belo Horizonte', max_length=255)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
    ]
