# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-05 00:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Pendente'), (1, 'Aprovado'), (2, 'Cancelado')], default=0, verbose_name='Situacao')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Inscricao',
                'verbose_name_plural': 'Inscricoes',
            },
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['nome_evento'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AddField(
            model_name='inscricao',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='eventos.Evento', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='inscricao',
            unique_together=set([('user', 'evento')]),
        ),
    ]
