# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-11 13:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20160804_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='T\xedtulo')),
                ('conteuto', models.TextField(verbose_name='Conte\xfado')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'ordering': ['-criado'],
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
            },
        ),
        migrations.AlterModelOptions(
            name='inscricao',
            options={'verbose_name': 'Inscri\xe7\xe3o', 'verbose_name_plural': 'Inscri\xe7\xf5es'},
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de t\xe9rmino'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descri\xe7\xe3o do Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='endereco',
            field=models.CharField(help_text='Para uma melhor localiza\ufffd\ufffdo no mapa, preencha sem abrevia\ufffd\ufffdes. Ex: Rua Martinho Estrela,  1229', max_length=255, verbose_name='Endere\xe7o'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_evento',
            field=models.IntegerField(blank=True, choices=[(0, 'Pago'), (1, 'Gratuito')], default=0, verbose_name='Tipo do Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='vagas_evento',
            field=models.IntegerField(blank=True, null=True, verbose_name='N\xfamero de vagas'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Pendente'), (1, 'Aprovado'), (2, 'Cancelado')], default=0, verbose_name='Situa\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to=settings.AUTH_USER_MODEL, verbose_name='Usu\xe1rio'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento', verbose_name='Evento'),
        ),
    ]
