# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-15 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20160811_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('embedded', models.TextField(blank=True, verbose_name='V\xeddeo embedded')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='palestras/materiais')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
            },
        ),
        migrations.CreateModel(
            name='Palestra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descri\xe7\xe3o')),
                ('numero', models.IntegerField(blank=True, default=0, verbose_name='N\xfamero (ordem)')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Data de libera\xe7\xe3o')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palestras', to='eventos.Evento', verbose_name='Evento')),
            ],
            options={
                'ordering': ['numero'],
                'verbose_name': 'Palestra',
                'verbose_name_plural': 'Palestras',
            },
        ),
        migrations.AlterField(
            model_name='aviso',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='eventos.Evento', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='material',
            name='palestra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='eventos.Palestra', verbose_name='Palestra'),
        ),
    ]
