# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-31 15:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160730_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name=b'Chave')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'Criado em')),
                ('confirmed', models.BooleanField(default=False, verbose_name=b'Confirmado?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'usuario')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Nova Senha',
                'verbose_name_plural': 'Novas Senhas',
            },
        ),
    ]
