# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-15 14:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160806_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usu\xe1rio', 'verbose_name_plural': 'Usu\xe1rios'},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name=b'Est\xc3\xa1 ativo?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name=b'\xc3\x89 da equipe?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile(b'^[\\w.@+-]+$'), b'O nome de usu\xc3\xa1rio s\xc3\xb3 pode conter letras, d\xc3\xadgitos ou os seguintes caracteres: @/./+/-/_', b'invalid')], verbose_name=b'Nome de Usu\xc3\xa1rio'),
        ),
    ]
