# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-17 13:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20160815_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile(b'^[\\w.@+-]+$'), b'O nome de usuario s\xc3\xb3 pode conter letras, d\xc3\xadgitos ou os seguintes caracteres: @/./+/-/_', b'invalid')], verbose_name=b'Nome de Usuario'),
        ),
    ]
